/**
 * Sync per-body audio stems from the folder contents.
 *
 * Scans public/audio/<bodyId>/ and regenerates src/data/audioStems.generated.ts:
 *   - *.m4a directly in the folder      -> body.stems
 *   - *.m4a in the folder's delay/ dir  -> body.delayedStems
 *
 * The audio folder is the source of truth: drop a stem file into a body's
 * folder and its config updates itself on the next build — no hand-edits to
 * bodies.ts. Bodies without an audio folder keep their pool-based config.
 *
 * Runs automatically on every `vite build`/dev start (wired in vite.config.ts).
 * Run manually: node scripts/sync-stems.mjs   (or: npm run sync:stems)
 */
import { readdirSync, statSync, writeFileSync, readFileSync, existsSync } from 'fs';
import { join, dirname } from 'path';
import { fileURLToPath } from 'url';

const here = dirname(fileURLToPath(import.meta.url));
const AUDIO_DIR = join(here, '..', 'public', 'audio');
const OUT_FILE = join(here, '..', 'src', 'data', 'audioStems.generated.ts');

const m4a = (dir) =>
  existsSync(dir) && statSync(dir).isDirectory()
    ? readdirSync(dir).filter((f) => f.toLowerCase().endsWith('.m4a')).sort()
    : [];

export function syncStems({ log = false } = {}) {
  const map = {};
  if (existsSync(AUDIO_DIR)) {
    for (const id of readdirSync(AUDIO_DIR).sort()) {
      const dir = join(AUDIO_DIR, id);
      if (!statSync(dir).isDirectory()) continue;
      map[id] = {
        stems: m4a(dir).map((f) => `${id}/${f}`),
        delayedStems: m4a(join(dir, 'delay')).map((f) => `${id}/delay/${f}`),
      };
    }
  }

  const body =
    `// AUTO-GENERATED by scripts/sync-stems.mjs — do not edit by hand.\n` +
    `// Regenerated on every \`vite build\`/dev start from the .m4a files in\n` +
    `// public/audio/<bodyId>/ (top level = stems, delay/ = delayedStems).\n` +
    `// Drop a stem into the folder and the audio config updates itself.\n` +
    `export const AUDIO_STEMS: Record<string, { stems: string[]; delayedStems: string[] }> =\n` +
    `${JSON.stringify(map, null, 2)};\n`;

  const changed = !existsSync(OUT_FILE) || readFileSync(OUT_FILE, 'utf8') !== body;
  if (changed) writeFileSync(OUT_FILE, body);
  if (log) {
    const withStems = Object.values(map).filter((b) => b.stems.length).length;
    console.log(
      `[sync-stems] ${Object.keys(map).length} folders, ${withStems} with stems — ` +
        (changed ? 'updated audioStems.generated.ts' : 'already up to date'),
    );
  }
  return { changed, bodies: map };
}

// Direct invocation: `node scripts/sync-stems.mjs`
if (process.argv[1] && process.argv[1].replace(/\\/g, '/').endsWith('scripts/sync-stems.mjs')) {
  syncStems({ log: true });
}
