// AUTO-GENERATED by scripts/sync-stems.mjs — do not edit by hand.
// Regenerated on every `vite build`/dev start from the .m4a files in
// public/audio/<bodyId>/ (top level = stems, delay/ = delayedStems).
// Drop a stem into the folder and the audio config updates itself.
export const AUDIO_STEMS: Record<string, { stems: string[]; delayedStems: string[] }> =
{
  "callisto": {
    "stems": [],
    "delayedStems": []
  },
  "ceres": {
    "stems": [],
    "delayedStems": []
  },
  "charon": {
    "stems": [],
    "delayedStems": []
  },
  "dione": {
    "stems": [],
    "delayedStems": []
  },
  "earth": {
    "stems": [
      "earth/Barker_Emaj-drone.m4a"
    ],
    "delayedStems": []
  },
  "enceladus": {
    "stems": [],
    "delayedStems": []
  },
  "eros": {
    "stems": [],
    "delayedStems": []
  },
  "europa": {
    "stems": [],
    "delayedStems": []
  },
  "ganymede": {
    "stems": [],
    "delayedStems": []
  },
  "iapetus": {
    "stems": [],
    "delayedStems": []
  },
  "io": {
    "stems": [],
    "delayedStems": []
  },
  "jupiter": {
    "stems": [
      "jupiter/Barker_Dmin-drone.m4a"
    ],
    "delayedStems": []
  },
  "mars": {
    "stems": [
      "mars/drone-01.m4a",
      "mars/texture-01.m4a",
      "mars/texture-02.m4a"
    ],
    "delayedStems": []
  },
  "mercury": {
    "stems": [
      "mercury/1DarkPolyPad.m4a",
      "mercury/2CasinoBlipsPad.m4a",
      "mercury/3FreudianPad.m4a",
      "mercury/4Lo-FiResoPad.m4a",
      "mercury/5RectangularBliss.m4a",
      "mercury/6-808Pure.m4a",
      "mercury/7AtlasKeys.m4a"
    ],
    "delayedStems": []
  },
  "mimas": {
    "stems": [],
    "delayedStems": []
  },
  "moon": {
    "stems": [],
    "delayedStems": []
  },
  "neptune": {
    "stems": [
      "neptune/drone-01.m4a",
      "neptune/pad-01.m4a"
    ],
    "delayedStems": []
  },
  "oberon": {
    "stems": [],
    "delayedStems": []
  },
  "phobos": {
    "stems": [],
    "delayedStems": []
  },
  "pluto": {
    "stems": [
      "pluto/Atotallydifferentthing.m4a"
    ],
    "delayedStems": []
  },
  "rhea": {
    "stems": [],
    "delayedStems": []
  },
  "saturn": {
    "stems": [
      "saturn/Barker_C-maj_arp_nord_SK5.m4a"
    ],
    "delayedStems": []
  },
  "sun": {
    "stems": [
      "sun/drone-01.m4a",
      "sun/texture-01.m4a"
    ],
    "delayedStems": []
  },
  "tethys": {
    "stems": [],
    "delayedStems": []
  },
  "titan": {
    "stems": [],
    "delayedStems": []
  },
  "titania": {
    "stems": [],
    "delayedStems": []
  },
  "triton": {
    "stems": [],
    "delayedStems": []
  },
  "uranus": {
    "stems": [
      "uranus/Barker_Gmin-drone.m4a"
    ],
    "delayedStems": []
  },
  "venus": {
    "stems": [
      "venus/AMBienT-19.m4a",
      "venus/pad-01.m4a",
      "venus/texture-01.m4a"
    ],
    "delayedStems": []
  },
  "vesta": {
    "stems": [],
    "delayedStems": []
  }
};
