// AUTO-GENERATED by scripts/sync-stems.mjs — do not edit by hand.
// Regenerated on every `vite build`/dev start from the .m4a files in
// public/audio/<bodyId>/ (top level = stems, delay/ = delayedStems).
// Drop a stem into the folder and the audio config updates itself.
export const AUDIO_STEMS: Record<string, { stems: string[]; delayedStems: string[] }> =
{
  "earth": {
    "stems": [
      "earth/Barker_Emaj-drone.m4a"
    ],
    "delayedStems": []
  },
  "jupiter": {
    "stems": [
      "jupiter/Barker_Dmin-drone.m4a"
    ],
    "delayedStems": []
  },
  "mars": {
    "stems": [
      "mars/drone-01.m4a",
      "mars/texture-01.m4a",
      "mars/texture-02.m4a"
    ],
    "delayedStems": []
  },
  "mercury": {
    "stems": [
      "mercury/1DarkPolyPad.m4a",
      "mercury/2CasinoBlipsPad.m4a",
      "mercury/3FreudianPad.m4a",
      "mercury/4Lo-FiResoPad.m4a",
      "mercury/5RectangularBliss.m4a",
      "mercury/6-808Pure.m4a",
      "mercury/7AtlasKeys.m4a"
    ],
    "delayedStems": []
  },
  "neptune": {
    "stems": [
      "neptune/drone-01.m4a",
      "neptune/pad-01.m4a"
    ],
    "delayedStems": []
  },
  "saturn": {
    "stems": [
      "saturn/Barker_C-maj_arp_nord_SK5.m4a"
    ],
    "delayedStems": []
  },
  "sun": {
    "stems": [
      "sun/drone-01.m4a",
      "sun/texture-01.m4a"
    ],
    "delayedStems": []
  },
  "uranus": {
    "stems": [
      "uranus/Barker_Gmin-drone.m4a"
    ],
    "delayedStems": []
  },
  "venus": {
    "stems": [
      "venus/pad-01.m4a",
      "venus/texture-01.m4a"
    ],
    "delayedStems": []
  }
};
